### ISSUE TITLE
Does not work on Alienware m15

### ISSUE THREAD

**Issue by shiecldk** [BjornRuytenberg/tcfp#2]
Hello, I am trying to disable the thunderbolt security level for macOS. However, Alienware m15 does not have the thunderbolt security level option in Bios. I found this script does not work with Alienware m15. I attach the prompts from the patch and the file.
File: http://www.mediafire.com/file/zcwtv8xbv2qg1ln/alienware_m15_tb.rom.zip/file

Parse:
user$ python3 ./tcfp.py parse ./tbdump.rom 
 2020-10-18 00:11:15,431 - WARNING - File size exceeds 229376 bytes. Controller may be unsupported.
 2020-10-18 00:11:15,431 - WARNING - No matching SL patterns for PCI ID '0x15da'. Ignoring PCI ID and trying all patterns instead.
 2020-10-18 00:11:15,431 - WARNING - No matching SL patterns found.
Vendor ID : 0xd4
PCI ID : 0x15da
PCI Device Name : JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
Model ID : 0x8a1
NVM version : 36 (0x24)
Vendor : Dell
Device : Alienware M15
Security Level : N/A

Patch:
user$ python3 ./tcfp.py patch ./tbdump.rom 
 2020-10-18 00:13:39,008 - WARNING - File size exceeds 229376 bytes. Controller may be unsupported.
 2020-10-18 00:13:39,009 - WARNING - No matching SL patterns for PCI ID '0x15da'. Ignoring PCI ID and trying all patterns instead.
 2020-10-18 00:13:39,009 - WARNING - No matching SL patterns found.
Vendor ID : 0xd4
PCI ID : 0x15da
PCI Device Name : JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
Model ID : 0x8a1
NVM version : 36 (0x24)
Vendor : Dell
Device : Alienware M15
Security Level : N/A

Error while processing firmware image:  PCI ID supported, but unable to parse current SL (different NVM version?). Aborting.`

Is there any way to fix it to patch the rom?

I also confirmed that the default security level is User Authorization (SL1) with Windows 10.

**Comment by BjornRuytenberg** [comment]
Hi,

Thanks a lot for your report and the attached dump. This allowed me to squash two bugs:
- Image size should be checked against both a lower and upper bound. Fixed in https://github.com/BjornRuytenberg/tcfp/commit/5c9616335a5fb97ba7dde79d49bf2dcbb951313c.
- SL heuristics wasn't working properly. Fixed in https://github.com/BjornRuytenberg/tcfp/commit/d8595340051b00ca1298d0cef29528024f7b3c7c.

I don't have access to a JHL6340 on NVM 36, but the good news is that your controller's image matched against a closely related model (JHL6540) on SL1. I'd say there's a fair chance patching will work, so please let me know.

If you grab the [latest version](https://github.com/BjornRuytenberg/tcfp/blob/master/tcfp.py), tcfp's output should show the following:

```
$ python3 tcfp.py parse tbdump.rom
 2020-10-18 18:55:53,617 - WARNING - No matching SL patterns for PCI ID '0x15da'. Ignoring PCI ID and trying all patterns instead.
Vendor ID : 0xd4
PCI ID : 0x15da
PCI Device Name : JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
Model ID : 0x8a1
NVM version : 36 (0x24)
Vendor : Dell
Device : Alienware M15
Security Level : SL1

$ python3 tcfp.py patch tbdump.rom
 2020-10-18 18:56:09,643 - WARNING - No matching SL patterns for PCI ID '0x15da'. Ignoring PCI ID and trying all patterns instead.
Vendor ID : 0xd4
PCI ID : 0x15da
PCI Device Name : JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
Model ID : 0x8a1
NVM version : 36 (0x24)
Vendor : Dell
Device : Alienware M15
Security Level : SL1

 2020-10-18 18:56:09,643 - WARNING - PCI ID unsupported, but current SL detected through heuristics. Patching may fail.
Image patched succesfully.

$ python3 tcfp.py parse tbdump.rom
Vendor ID : 0xd4
PCI ID : 0x15da
PCI Device Name : JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016]
Model ID : 0x8a1
NVM version : 36 (0x24)
Vendor : Dell
Device : Alienware M15
Security Level : SL0
```

> Hello, I am trying to disable the thunderbolt security level for macOS.

I suppose you mean a Hackintosh setup? Would be interesting to hear what you find -- I haven't tested these kind of setups, yet.

**Comment by BjornRuytenberg** [comment]
Any luck? If you can confirm that this works for you, I'll add these signatures as being valid for your controller config as well. Otherwise, I'd be happy to analyze this issue further.

**Comment by BjornRuytenberg** [comment]
I'm afraid I can't help you without further info. Closing this issue.
